export const PERMISSION_NAME_PATTERN =
  /^[A-Z][A-Z0-9_]*(?:\.[A-Z][A-Z0-9_]*)+$/;

export const DEFAULT_PERMISSIONS = [
  'SALE.CREATE',
  'SALE.ROUND.CREATE',
  'SALE.STATUS.UPDATE',
  'SALE.DRAFT.VIEW',
  'SALE.DRAFT.MANAGE',

  'INVOICE.PAYMENT.RECORD',

  'RECEIPT.MANUAL.CREATE',
  'RECEIPT.GENERATE',
  'RECEIPT.PRINT',

  'TICKET.STATUS.UPDATE',

  'CUSTOMER.VIEW',
  'CUSTOMER.MANAGE',

  'TABLE.VIEW',
  'TABLE.MANAGE',
  'TABLE.STATUS.UPDATE',

  'PROMOTION.VIEW',
  'PROMOTION.MANAGE',

  'DASHBOARD.VIEW',

  'REPORT.VIEW',

  'REFUND.VIEW',
  'REFUND.APPROVE',

  'PROJECTS.READ',
  'PROJECTS.CREATE',
  'PROJECTS.UPDATE',
  'PROJECTS.DELETE',

  'TECHNOLOGIES.READ',
  'TECHNOLOGIES.CREATE',
  'TECHNOLOGIES.UPDATE',
  'TECHNOLOGIES.DELETE',

  'NOTIFICATIONS.READ',
  'NOTIFICATIONS.CREATE',
  'NOTIFICATIONS.RETRY',
] as const;

export type DefaultPermission = (typeof DEFAULT_PERMISSIONS)[number];
